import React from 'react';
import { createPortal } from 'react-dom';
import { AnalysisSession, AnalysisResponse } from '../types';

interface PrintLayoutProps {
  sessions: AnalysisSession[];
}

const formatTextToHtml = (text: string) => {
    if (!text) return "";
    return text
        .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
        .replace(/\n/g, '<br/>');
};

export const PrintLayout: React.FC<PrintLayoutProps> = ({ sessions }) => {
  // Filter only successful sessions that have results
  const validSessions = sessions.filter(s => s.status === 'SUCCESS' && s.result);
  const refNo = `KKM/PKP/2025/${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`;
  const today = new Date().toLocaleDateString('ms-MY', { day: 'numeric', month: 'long', year: 'numeric' });

  // Get the portal target
  const printMount = document.getElementById('print-mount');
  
  if (!printMount) return null;

  // A4 Page Style
  // 210mm Width, 297mm Height.
  // We use padding 20mm
  const pageStyle = "w-[794px] min-h-[1123px] bg-white text-black p-[20mm] mx-auto relative shadow-xl print:shadow-none print:w-full print:h-auto print:p-[20mm] box-border";

  const handleBack = () => {
    document.body.classList.remove('is-printing');
  };

  return createPortal(
    <div className="w-full bg-gray-100 print:bg-white flex flex-col items-center gap-8 print:block print:gap-0 font-sans">
      
      {/* 
         HALAMAN 1: SURAT RASMI (COVER LETTER)
      */}
      <div className={`${pageStyle} print-page-break-after flex flex-col`}>
          
          {/* LOGO & LETTERHEAD */}
          <div className="flex items-start justify-between border-b-[3px] border-double border-black pb-6 mb-8 avoid-break cursor-pointer" onClick={handleBack}>
                <div className="flex items-center gap-4">
                    <img src="/jata_negara.png" alt="Jata Negara" className="h-24 w-auto object-contain fallback-logo" onError={(e) => {
                        e.currentTarget.style.display = 'none';
                        const div = e.currentTarget.nextElementSibling as HTMLDivElement;
                        if (div) div.style.display = 'flex';
                    }}/>
                    <div className="h-24 w-24 border border-black rounded-full hidden flex-col items-center justify-center p-2 text-center shadow">
                       <span className="font-extrabold text-[10px] block leading-tight">SILA MUAT<br/>NAIK<br/>JATA NEGARA</span>
                    </div>
                    <div>
                        <h1 className="text-xl font-extrabold uppercase tracking-wide text-black leading-tight">KEMENTERIAN KESIHATAN MALAYSIA</h1>
                        <p className="text-sm font-bold text-black uppercase">Unit Inspektorat Kesihatan Awam</p>
                        <p className="text-xs text-black">Hospital Sultan Haji Ahmad Shah</p>
                        <p className="text-xs text-black">Jalan Temerloh - Maran, 28000 Temerloh, Pahang</p>
                    </div>
                </div>
                <div className="text-right text-[10px] font-mono mt-2">
                    <p>Generated by:</p>
                    <p className="font-bold">VECTORGUARD AI</p>
                </div>
          </div>

          {/* REFERENCE BLOCK */}
          <div className="flex justify-between text-sm mb-10 text-black font-sans avoid-break">
                <div className="space-y-1">
                   <p><span className="font-bold w-20 inline-block">Rujukan:</span> {refNo}</p>
                   <p><span className="font-bold w-20 inline-block">Bil:</span> 001</p>
                   <p><span className="font-bold w-20 inline-block">Tarikh:</span> {today}</p>
                </div>
                <div className="text-right">
                   {/* SULIT & PERSENDIRIAN removed */}
                </div>
          </div>

          {/* RECIPIENT */}
          <div className="mb-8 text-black font-sans leading-relaxed avoid-break">
                <p className="font-bold">Kepada:</p>
                <p>Radicare (M) Sdn Bhd dan vendor yang berkenaan,</p>
                <p>Serta Pemilik / Penghuni / Pemegang Lesen / Pihak Pengurusan,</p>
                <p className="mt-4">Tuan/Puan,</p>
          </div>

          {/* TITLE */}
          <div className="mb-8 text-black text-center avoid-break">
                <h2 className="text-lg font-extrabold underline uppercase mb-2">NOTIS PEMERIKSAAN DAN ARAHAN PEMBERSIHAN PREMIS</h2>
                <p className="text-xs italic">(Di bawah Akta Pemusnahan Serangga Pembawa Penyakit 1975 & Akta Kilang dan Jentera 1967)</p>
          </div>

          {/* BODY TEXT */}
          <div className="text-sm text-justify leading-relaxed text-black font-serif space-y-4 mb-8">
              <p>
                 Dengan segala hormatnya perkara di atas adalah dirujuk.
              </p>
              <p>
                 2. Pemeriksaan yang telah dijalankan pada tarikh di atas melalui sistem imbasan pintar <b>VectorGuard AI</b> mendapati premis tuan/puan berada dalam keadaan yang berpotensi membiakkan serangga pembawa penyakit, mendatangkan kacauganggu awam, atau melanggar piawaian keselamatan pekerjaan (OSH).
              </p>
              <p>
                 3. Sehubungan dengan itu, tuan/puan dikehendaki mengambil tindakan pembetulan serta-merta terhadap penemuan-penemuan yang disenaraikan dalam <b>Lampiran Bergambar</b> yang disertakan bersama surat ini. Kegagalan mematuhi arahan ini boleh menyebabkan tindakan perundangan diambil.
              </p>
              <p>
                 Kerjasama tuan/puan dalam menjaga kesihatan awam amatlah dihargai.
              </p>
              <p className="font-bold mt-4">"BERKHIDMAT UNTUK NEGARA"</p>
          </div>

          {/* SIGNATURE */}
          <div className="mt-auto avoid-break">
               <p className="font-bold text-sm uppercase mb-12">Saya yang menjalankan amanah,</p>
               <div className="border-b border-black w-64 mb-2"></div>
               <p className="font-bold text-sm uppercase">Muhammad Ismail Bin Ab Rahman</p>
               <p className="text-sm">Pembantu Kesihatan Awam Kanan</p>
               <p className="text-sm">Unit Kesihatan Awam</p>
               <p className="text-sm">HoSHAS</p>
          </div>
      </div>

      {/* 
         HALAMAN 2: RUMUSAN KUMULATIF KESELURUHAN (NEW PAGE)
      */}
      {validSessions.length > 0 && (() => {
          const totalPoints = validSessions.length;
          const avgHygiene = Math.round(validSessions.reduce((sum, s) => sum + (s.result?.hygieneLevel || 0), 0) / (totalPoints || 1) * 10) / 10;
          const avgSafety = Math.round(validSessions.reduce((sum, s) => sum + (s.result?.safetyLevel || s.result?.hygieneLevel || 0), 0) / (totalPoints || 1) * 10) / 10;
          const isFailing = avgHygiene >= 3 || avgSafety >= 3;
          let verdict = isFailing ? "TIDAK MEMUASKAN & KRITIKAL" : "MEMUASKAN & TERKAWAL";
          let actionLabel = isFailing ? "NOTIS AMARAN / KOMPAUN" : "TIADA TINDAKAN LANJUT";

          return (
              <div className={`${pageStyle} print-page-break-after flex flex-col`}>
                  <div className="border-b border-black pb-2 mb-6 flex justify-between items-end text-xs font-bold uppercase">
                      <span className="text-lg">RUMUSAN KUMULATIF PREMIS</span>
                      <span>REF: {refNo}</span>
                  </div>

                  <div className="mb-6 avoid-break text-sm text-justify font-serif text-black leading-relaxed">
                      Laporan ini adalah berasaskan penilaian menyeluruh ke atas <b>{totalPoints}</b> titik sampel/imej dalam premis ini. Markah di bawah adalah purata agregat sebagai gambaran adil dan holistik tahap pematuhan keseluruhan.
                  </div>

                  {/* KOTAK SKOR PURATA */}
                  <div className="grid grid-cols-2 gap-4 mb-8 avoid-break">
                      <div className="border-[3px] border-black p-4 text-center bg-gray-50 flex flex-col items-center justify-center">
                          <div className="text-xs uppercase font-bold text-gray-800 mb-1">PURATA SKOR KEBERSIHAN</div>
                          <div className="text-5xl font-extrabold mb-1">{avgHygiene.toFixed(1)} <span className="text-lg">/ 5</span></div>
                          <div className="text-xs font-bold uppercase mt-1 tracking-wider">{avgHygiene >= 3 ? 'GAGAL' : 'LULUS'}</div>
                      </div>
                      <div className="border-[3px] border-black p-4 text-center bg-gray-50 flex flex-col items-center justify-center">
                          <div className="text-xs uppercase font-bold text-gray-800 mb-1">PURATA SKOR KESELAMATAN</div>
                          <div className="text-5xl font-extrabold mb-1">{avgSafety.toFixed(1)} <span className="text-lg">/ 5</span></div>
                          <div className="text-xs font-bold uppercase mt-1 tracking-wider">{avgSafety >= 3 ? 'GAGAL' : 'LULUS'}</div>
                      </div>
                  </div>

                  {/* JADUAL PERINCIAN SETIAP IMEJ */}
                  <div className="flex-1 avoid-break">
                      <h4 className="font-bold text-sm border-b border-black mb-3 pb-1 uppercase">Pecahan Markah Setiap Kedudukan:</h4>
                      <table className="w-full text-xs border-collapse border border-black mb-4">
                          <thead>
                              <tr className="bg-gray-200">
                                  <th className="border border-black p-2 w-10 text-center">BIL</th>
                                  <th className="border border-black p-2 text-left">LOKASI / REFERENS FAIL</th>
                                  <th className="border border-black p-2 text-center w-24">KEBERSIHAN</th>
                                  <th className="border border-black p-2 text-center w-24">KESELAMATAN</th>
                                  <th className="border border-black p-2 text-left">ISU UTAMA DOMINAN</th>
                              </tr>
                          </thead>
                          <tbody>
                              {validSessions.map((s, idx) => {
                                  const r = s.result!;
                                  const dominantRisk = r.risks?.[0];
                                  return (
                                      <tr key={s.id} className={r.hygieneLevel >= 3 || (r.safetyLevel && r.safetyLevel >= 3) ? "bg-red-50 print:bg-transparent" : ""}>
                                          <td className="border border-black p-2 text-center font-bold">{idx + 1}</td>
                                          <td className="border border-black p-2 truncate max-w-[200px]" title={s.fileName}>{s.fileName || `Imej ${idx + 1}`}</td>
                                          <td className={`border border-black p-2 text-center font-bold ${r.hygieneLevel >= 3 ? 'text-red-600' : ''}`}>{r.hygieneLevel}/5</td>
                                          <td className={`border border-black p-2 text-center font-bold ${(r.safetyLevel || r.hygieneLevel) >= 3 ? 'text-red-600' : ''}`}>{r.safetyLevel || r.hygieneLevel}/5</td>
                                          <td className="border border-black p-2 text-[10px] uppercase truncate max-w-[200px]">
                                              {dominantRisk ? dominantRisk.label : "TIADA ISU KRITIKAL"}
                                          </td>
                                      </tr>
                                  );
                              })}
                          </tbody>
                      </table>
                  </div>

                  <div className="border-[3px] border-double border-black p-4 bg-gray-100 print:bg-white text-center mt-6 avoid-break">
                      <div className="text-xs font-bold uppercase mb-1 underline">KEPUTUSAN KESELURUHAN MAKMAL AI</div>
                      <div className="text-lg font-extrabold pb-2">{verdict}</div>
                      <div className="text-xs uppercase font-serif mt-2 border-t border-gray-400 pt-2">TINDAKAN CADANGAN: <b>{actionLabel}</b></div>
                  </div>

                  {/* Footer Halaman */}
                  <div className="mt-auto pt-4 border-t border-black text-[10px] flex justify-between">
                      <span>Muka Surat 2 daripada {validSessions.length + 2}</span>
                      <span>Dicetak pada: {new Date().toLocaleString()}</span>
                  </div>
              </div>
          )
      })()}

      {/* 
         HALAMAN LAMPIRAN (DYNAMIC)
      */}
      {validSessions.map((session, index) => {
          const result = session.result!;
          const risks = result.risks || []; // DEFENSIVE CHECK HERE

          return (
            <div key={session.id} className={`${pageStyle} print-page-break-after flex flex-col`}>
                {/* Header Lampiran */}
                <div className="border-b border-black pb-2 mb-6 flex justify-between items-end text-xs font-bold uppercase">
                    <span className="text-lg">LAMPIRAN {index + 1}</span>
                    <span>REF: {refNo}</span>
                </div>

                {/* Info Lokasi */}
                <div className="bg-gray-100 p-3 mb-6 border-l-4 border-black avoid-break print:bg-gray-50">
                    <h3 className="font-bold text-sm uppercase">LOKASI PEMERIKSAAN:</h3>
                    <p className="text-xs">{session.fileName}</p>
                </div>

                {/* GAMBAR BUKTI UTAMA BERSERTA ANNOTASI */}
                {/* Inline blocks let us perfectly map percentages coordinates on image */}
                <div className="mb-6 w-full flex flex-col gap-4 avoid-break">
                    <div className="w-full p-2 border border-black bg-gray-50 flex items-center justify-center">
                        <div className="relative inline-block max-w-full">
                            <img 
                                src={session.imageSrc} 
                                className="max-h-[350px] max-w-full block" 
                                alt={`Bukti Pemeriksaan ${index + 1}`} 
                            />
                            {/* Annotations for each risk */}
                            {risks.map((risk, rIdx) => {
                                if (!risk.box_2d || typeof risk.box_2d.xmin !== 'number') return null;
                                const box = risk.box_2d;
                                
                                const isHygiene = risk.category === 'HYGIENE';
                                const isSafety = risk.category === 'SAFETY';
                                const colorHex = isHygiene ? '#d97706' : (isSafety ? '#ca8a04' : '#dc2626'); // amber, yellow, red
                                
                                return (
                                    <div 
                                        key={risk.id}
                                        className="absolute border-[2px]"
                                        style={{
                                            top: `${Math.max(0, Math.min(100, box.ymin / 10))}%`,
                                            left: `${Math.max(0, Math.min(100, box.xmin / 10))}%`,
                                            width: `${Math.max(2, Math.min(100, (box.xmax - box.xmin) / 10))}%`,
                                            height: `${Math.max(2, Math.min(100, (box.ymax - box.ymin) / 10))}%`,
                                            borderColor: colorHex,
                                            backgroundColor: `${colorHex}33`, 
                                            WebkitPrintColorAdjust: 'exact', 
                                            printColorAdjust: 'exact'
                                        }}
                                    >
                                        <div 
                                            className="absolute -top-3 -left-3 w-5 h-5 flex items-center justify-center text-[10px] font-bold rounded-sm text-white z-10 print:!text-white border print:!border-black"
                                            style={{ 
                                                backgroundColor: colorHex,
                                                borderColor: 'rgba(0,0,0,0.5)',
                                                WebkitPrintColorAdjust: 'exact', 
                                                printColorAdjust: 'exact'
                                            }}
                                        >
                                            {rIdx + 1}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                    {session.simulationImage && (
                        <div>
                            <h4 className="font-bold text-xs border-b border-gray-300 mb-1 pb-1 uppercase">SIMULASI AI (CADANGAN PEMBAIKAN):</h4>
                            <div className="w-full p-2 border border-black bg-gray-50 flex items-center justify-center">
                                <img 
                                    src={session.simulationImage} 
                                    className="max-h-[350px] max-w-full block" 
                                    alt={`Simulasi AI ${index + 1}`} 
                                    crossOrigin="anonymous"
                                />
                            </div>
                        </div>
                    )}
                </div>

                {/* Skor Kotak */}
                <div className="grid grid-cols-2 gap-4 mb-6 avoid-break">
                    <div className="border border-black p-4 text-center">
                        <div className="text-xs uppercase font-bold text-gray-600 mb-1">SKOR KEBERSIHAN</div>
                        <div className="text-3xl font-extrabold">{result.hygieneLevel}/5</div>
                        <div className="text-[10px] mt-1 uppercase tracking-wider">{result.hygieneLevel >= 3 ? 'GAGAL / KRITIKAL' : 'LULUS / MEMUASKAN'}</div>
                    </div>
                    <div className="border border-black p-4 text-center">
                        <div className="text-xs uppercase font-bold text-gray-600 mb-1">SKOR KESELAMATAN</div>
                        <div className="text-3xl font-extrabold">{result.safetyLevel || result.hygieneLevel}/5</div>
                        <div className="text-[10px] mt-1 uppercase tracking-wider">{(result.safetyLevel || result.hygieneLevel) >= 3 ? 'BERISIKO TINGGI' : 'TERKAWAL'}</div>
                    </div>
                </div>

                {/* Ulasan AI */}
                <div className="mb-6 avoid-break">
                     <h4 className="font-bold text-sm border-b border-gray-300 mb-2 pb-1 uppercase">ULASAN HASIL PEMERIKSAAN:</h4>
                     <div 
                        className="text-xs text-justify font-serif leading-relaxed text-black"
                        dangerouslySetInnerHTML={{ __html: formatTextToHtml(result.generalAdvice) }}
                     />
                </div>

                {/* Senarai Risiko */}
                <div className="flex-1 avoid-break">
                    <h4 className="font-bold text-sm border-b border-gray-300 mb-2 pb-1 uppercase">SENARAI KESALAHAN YANG DITEMUI:</h4>
                    <table className="w-full text-xs border-collapse border border-black">
                        <thead>
                            <tr className="bg-gray-200 print:bg-gray-100">
                                <th className="border border-black p-2 text-left w-8">#</th>
                                <th className="border border-black p-2 text-left w-1/4">JENIS / LABEL</th>
                                <th className="border border-black p-2 text-left">TINDAKAN PEMBETULAN</th>
                            </tr>
                        </thead>
                        <tbody>
                            {risks.slice(0, 6).map((risk, rIdx) => (
                                <tr key={rIdx}>
                                    <td className="border border-black p-2 text-center">{rIdx + 1}</td>
                                    <td className="border border-black p-2 font-bold uppercase text-red-700">
                                        {risk.label}
                                        <div className="text-[9px] text-black font-normal mt-1 italic">{risk.agent}</div>
                                    </td>
                                    <td className="border border-black p-2 italic">{risk.solution}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                    {risks.length > 6 && <p className="text-[10px] italic mt-1 text-right">...dan {risks.length - 6} kesalahan lain.</p>}
                </div>

                {/* Footer Halaman */}
                <div className="mt-auto pt-4 border-t border-black text-[10px] flex justify-between">
                    <span>Muka Surat {index + 2} daripada {validSessions.length + 1}</span>
                    <span>Dicetak pada: {new Date().toLocaleString()}</span>
                </div>
            </div>
          );
      })}
    </div>,
    printMount
  );
};
